Repository Anushka-Bhowmick/Supnits-Classes, pull requests merged in 2024-01, with the labels that each got.

#7 Fixed image loading issue in multiple pages
  src/components/about/leaders/Leaders.js
  src/components/about/teachers/Data.js
  src/components/about/teachers/Teachers.js
  src/components/blogs/sections/section1/Section1.js
  src/components/blogs/sections/section2/Section2.js
  src/components/blogs/sections/section3/Section3.js
  src/components/landing/testimonials/Tes.js
Labels: apertre, easy, points: 5

#41 Scroll bar changed and Emailjs added as it was missing
  package-lock.json
  package.json
  public/style.css
Labels: apertre, easy, points: 5

#49 #2 Added light and dark mode button
  src/ThemeProvider.js
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/navbar/ThemeProvider.js
  src/components/navbar/dark-mode.css
  src/dark-mode.css
  src/index.js
Labels: apertre, hard, points: 15

#50 Update README.md
  README.md
Labels: apertre, easy
